#!/usr/bin/env bash

# Get Emscripten SDK sysroot path
SYSROOT="${EMSDK}/upstream/emscripten/cache/sysroot"

# Build additional flags
EXTRA_FLAGS="-nostdinc -nostdinc++ --sysroot=$SYSROOT -isystem $SYSROOT/include/compat -isystem $SYSROOT/include"

params="$@"
calling=$(echo "$params" | grep -q "\-x c++" && echo "em++ $EXTRA_FLAGS $params" || echo "emcc $EXTRA_FLAGS $params")
>&2 echo "calling ${calling}"
${calling}
