#!/usr/bin/env bash
# adding SIDE_MODULE & LINKABLE beacuse if this program is called it's probably by one of the ocaml wrappers, and we need partial libraries
params="$@"
calling=$(echo "$params" | grep -q "\-x c++" && echo "em++ $params" || echo "emcc $params")
>&2 echo "calling ${calling}"
${calling}

# put a comment here because i'm not sure if this is useful but don't want to remove it
# SYSROOT=/home/rboudrouss/Documents/emsdk/upstream/emscripten/cache/sysroot
# --sysroot=$SYSROOT -isystem $SYSROOT/include/compat -isystem $SYSROOT/include/compat -I/usr/lib/gcc/x86_64-pc-linux-gnu/14.2.1/include -I/usr/include -nostdinc -nostdinc++ 