/**
 * Test file for the Clang JSON to OCaml AST translator
 * 
 * This tests the parser with a simple C program to verify
 * the translation produces valid OCaml AST structures.
 */

import { mlclang_parse_json } from './clang_parser_ml';
import type { ASTNode } from './clang_ast_json';

// Example JSON AST for: int main() { return 0; }
// Generated by: clang -cc1 -ast-dump=json -x c test.c
const SIMPLE_MAIN_AST: ASTNode = {
    "id": "0x1",
    "kind": "TranslationUnitDecl",
    "loc": {},
    "range": { "begin": {}, "end": {} },
    "inner": [
        {
            "id": "0x2",
            "kind": "FunctionDecl",
            "loc": {
                "offset": 0,
                "file": "test.c",
                "line": 1,
                "col": 5,
                "tokLen": 4
            },
            "range": {
                "begin": { "offset": 0, "col": 1, "tokLen": 3 },
                "end": { "offset": 22, "col": 23, "tokLen": 1 }
            },
            "name": "main",
            "mangledName": "main",
            "type": { "qualType": "int ()" },
            "inner": [
                {
                    "id": "0x3",
                    "kind": "CompoundStmt",
                    "range": {
                        "begin": { "offset": 13, "col": 14, "tokLen": 1 },
                        "end": { "offset": 22, "col": 23, "tokLen": 1 }
                    },
                    "inner": [
                        {
                            "id": "0x4",
                            "kind": "ReturnStmt",
                            "range": {
                                "begin": { "offset": 15, "col": 16, "tokLen": 6 },
                                "end": { "offset": 22, "col": 23, "tokLen": 1 }
                            },
                            "inner": [
                                {
                                    "id": "0x5",
                                    "kind": "IntegerLiteral",
                                    "range": {
                                        "begin": { "offset": 22, "col": 23, "tokLen": 1 },
                                        "end": { "offset": 22, "col": 23, "tokLen": 1 }
                                    },
                                    "type": { "qualType": "int" },
                                    "value": "0"
                                }
                            ]
                        }
                    ]
                }
            ]
        }
    ]
};

/**
 * Run parser test
 */
function runTest(): void {
    console.log('=== Clang JSON to OCaml AST Test ===\n');
    
    console.log('Input: int main() { return 0; }');
    console.log('\nParsing JSON AST...\n');
    
    try {
        const result = mlclang_parse_json(JSON.stringify(SIMPLE_MAIN_AST), 'test.c');
        
        console.log('Parse result type:', typeof result);
        console.log('Parse result:', JSON.stringify(result, null, 2));
        
        // Check the structure
        if (Array.isArray(result) && result.length === 6) {
            console.log('\n✓ Result is a 5-tuple (6 elements with tag)');
            console.log('  - Tag:', result[0]);
            console.log('  - parse_decl type:', typeof result[1]);
            console.log('  - parse_diag type:', typeof result[2]);
            console.log('  - parse_comments type:', typeof result[3]);
            console.log('  - parse_macros type:', typeof result[4]);
            console.log('  - parse_files type:', typeof result[5]);
        } else {
            console.log('\n✗ Unexpected result structure');
        }
        
        console.log('\n=== Test Complete ===');
    } catch (error) {
        console.error('Test failed with error:', error);
    }
}

// Run the test
runTest();

export { runTest, SIMPLE_MAIN_AST };

